### ISSUE TITLE
No module named 'lib' when running pytorch ppo_play.py

### ISSUE THREAD

**Issue by HuXinpengFigo** [Ostyk/walk-bot#1]
hello, would you please help me about that lossing library problem.
Because my mujoco version is 200,  i cannot install baselines by pip3, which said it requires mujoco150. So I install baslines from openai's github repository.
after that when i running python3 ppo_play.py, it returns me 
'Traceback (most recent call last):
  File "ppo_play.py", line 6, in <module>
    from lib.model import ActorCritic
ModuleNotFoundError: No module named 'lib''
i want to know how to solve this problem, do i have to install other environment?
think you.

**Comment by Ostyk** [comment]
Hi Sorry, I mistakenly used a gitignore template which had `lib/` in it. This resulted in those files not being pushed. I have added them now. Reopen the issue if need be.
